# Server related properties
server:
    port: 6443
    servlet:
        context-path: /rest4cep

# Spring related properties
spring:
    profiles:
        active: rest4cep
    jpa:
        open-in-view: false
        show-sql: false
    data:
        mongodb:
            host: localhost
            port: 27017
            authentication-database: MongoDataBaseName
            database: MongoDataBaseName
            username: MongoUser
            password: MongoPassword
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/rest4cep?useSSL=false
        username: rest4cep
        password: pswrdRest4Cep