server:
    port: 6443
    servlet:
        context-path: /rest4cep
spring:
    data:
        mongodb:
            host: angelgamaza.es
            port: 3305
            authentication-database: rest4cep
            database: rest4cep
            username: rest4cep
            password: REST4CEP.2020$
    datasource:
        url: jdbc:mysql://angelgamaza.es/rest4cep?useSSL=false
        username: rest4cep
        password: REST4CEP.2020$
        
